package com.mycompany.csc261pokedexfinalproject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Cameron
 */
public class PokemonQuiz extends javax.swing.JPanel {

    /**
     * Creates new form PokemonQuiz
     */
    public PokemonQuiz() {
        initComponents();
        this.setBackground(new java.awt.Color(217, 76, 56)); // Set the background color using RGB values
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        howToPlayButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        whosThatPokemonLabel = new javax.swing.JLabel();
        guessEntererLabel = new javax.swing.JLabel();
        guessEntererTextField = new javax.swing.JTextField();
        guessesLeftLabel = new javax.swing.JLabel();
        guessesLeftTextField = new javax.swing.JTextField();
        playQuizButton = new javax.swing.JButton();
        retryQuizButton = new javax.swing.JButton();

        howToPlayButton.setText("How to Play!");
        howToPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlayButtonActionPerformed(evt);
            }
        });

        whosThatPokemonLabel.setFont(new java.awt.Font("Pokemon Solid", 0, 36)); // NOI18N
        whosThatPokemonLabel.setText("Who's that Pokémon? ");

        guessEntererLabel.setText("Enter your guess:");

        guessEntererTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessEntererTextFieldActionPerformed(evt);
            }
        });

        guessesLeftLabel.setText("Guesses left:");

        guessesLeftTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessesLeftTextFieldActionPerformed(evt);
            }
        });

        playQuizButton.setText("Play!");

        retryQuizButton.setText("Retry");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playQuizButton)
                        .addGap(59, 59, 59)
                        .addComponent(retryQuizButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guessEntererLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guessEntererTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guessesLeftLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guessesLeftTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(howToPlayButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(whosThatPokemonLabel)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(howToPlayButton)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(whosThatPokemonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessEntererLabel)
                    .addComponent(guessEntererTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessesLeftLabel)
                    .addComponent(guessesLeftTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playQuizButton)
                    .addComponent(retryQuizButton))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guessEntererTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessEntererTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guessEntererTextFieldActionPerformed

    private void guessesLeftTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessesLeftTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guessesLeftTextFieldActionPerformed

    private void howToPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_howToPlayButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel guessEntererLabel;
    private javax.swing.JTextField guessEntererTextField;
    private javax.swing.JLabel guessesLeftLabel;
    private javax.swing.JTextField guessesLeftTextField;
    private javax.swing.JButton howToPlayButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton playQuizButton;
    private javax.swing.JButton retryQuizButton;
    private javax.swing.JLabel whosThatPokemonLabel;
    // End of variables declaration//GEN-END:variables
}
